authors:
  john0isaac:
    name: John Aziz # Author name
    description: Software and Data Engineer, Microsoft AI MVP # Author description
    avatar: /images/avatar.jpeg # Author avatar
    url: https://linkedin.com/in/john0isaac # Author URL
