name: Test Jekyll Site

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Lint Markdown
        run: |
          npm install -g markdownlint-cli
          markdownlint '**/*.md' || echo 'markdownlint warnings only'
